# Build configuration for Google Cloud Build
steps:
  # Step 1: Build Backend
  - name: 'node:18'
    id: 'build-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        # Use npm install instead of ci since package-lock.json might be missing
        npm install
        # Install TypeScript locally if not in dependencies
        npm install typescript --save-dev
        npm run build
    
  # Step 2: Build WebAssembly
  - name: 'node:18'
    id: 'build-wasm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend/wasm
        npm install
        npm run asbuild:release
        # Create public directory if it doesn't exist
        mkdir -p ../public
        cp build/release.wasm ../public/formulae.wasm
        cp build/release.js ../public/formulae.js
  
  # Step 3: Build Frontend
  - name: 'node:18'
    id: 'build-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        echo "REACT_APP_API_URL=https://cs144-webapps-ryanrosario-sp25.appspot.com/api" > .env.production
        npm install
        npm run build
    waitFor: ['build-wasm']
  
  # Step 4: Copy frontend to backend/public
  - name: 'ubuntu'
    id: 'copy-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        rm -rf backend/public
        mkdir -p backend/public
        cp -r frontend/build/* backend/public/
        echo "Contents of backend/public:"
        ls -la backend/public
    waitFor: ['build-frontend', 'build-backend']
  
  # Step 5: Prepare for deployment
  - name: 'node:18'
    id: 'prepare-deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        # Remove dev dependencies to reduce deployment size
        npm prune --production
        # Ensure dist exists
        ls -la dist/
    waitFor: ['copy-frontend']
  
  # Step 6: Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'backend/app.yaml'
      - '--project=cs144-webapps-ryanrosario-sp25'
      - '--quiet'
      - '--promote'
      - '--version=prod'
    waitFor: ['prepare-deploy']

timeout: '2000s'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'