# Google App Engine configuration for NutriBruin Backend
runtime: nodejs18
env: standard

# Instance configuration - F1 for cost optimization
instance_class: F1

# Auto-scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.7
  min_instances: 0  # Scale to zero when not in use
  max_instances: 10
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30s
  max_pending_latency: automatic
  max_concurrent_requests: 50

# Environment variables (non-sensitive only)
env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  FRONTEND_URL: "https://cs144-webapps-ryanrosario-sp25.appspot.com"
  SCRAPER_ENABLED: "true"
  SCRAPER_SCHEDULE: "0 11 * * *"  

# Request handlers
handlers:
  # Health check endpoint
  - url: /_ah/health
    script: auto
    secure: always

  # Static files (if any)
  - url: /static
    static_dir: public
    secure: always
    expiration: "7d"
    http_headers:
      Cache-Control: "public, max-age=604800"

  # API routes
  - url: /api/.*
    script: auto
    secure: always

  # Scraper health check
  - url: /api/scraper/health
    script: auto
    secure: always

  # Root endpoint
  - url: /.*
    script: auto
    secure: always

# Warmup requests to reduce cold starts
inbound_services:
  - warmup

# VPC connector for MongoDB Atlas and Redis Cloud
vpc_access_connector:
  name: projects/nutri-bruin-cs144/locations/us-central1/connectors/nutribruin-connector

# Health check configuration
readiness_check:
  path: "/api/health"
  check_interval_sec: 10
  timeout_sec: 5
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 5
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300