# deploy/cloud-run/service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nutri-bruin-scraper
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 600
      serviceAccountName: nutri-bruin-scraper@YOUR-PROJECT-ID.iam.gserviceaccount.com
      containers:
      - image: gcr.io/YOUR-PROJECT-ID/nutri-bruin-scraper
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri
              key: latest
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-host
              key: latest
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redis-port
              key: latest
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: latest