name: Deploy to Google App Engine

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: cs144-webapps-ryanrosario-sp25
  NODE_VERSION: '18'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and Build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    # Skip cache to avoid errors - npm install is fast enough
    
    # Install Backend
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install
    
    # Build Backend
    - name: Build backend TypeScript
      working-directory: ./backend
      run: npm run build
    
    # Test Backend
    - name: Run backend tests
      working-directory: ./backend
      run: npm test -- --passWithNoTests || true
    
    # Install Frontend
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install
    
    # Build WebAssembly
    - name: Build WebAssembly module
      working-directory: ./frontend/wasm
      run: |
        npm install
        npm run asbuild:release
        mkdir -p ../public
        cp build/release.wasm ../public/formulae.wasm
        cp build/release.js ../public/formulae.js
    
    # Build Frontend
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      env:
        REACT_APP_API_URL: https://${{ env.PROJECT_ID }}.appspot.com/api
        CI: false
    
    # Prepare deployment
    - name: Prepare deployment package
      run: |
        rm -rf backend/public
        mkdir -p backend/public
        cp -r frontend/build/* backend/public/
        echo "Contents of backend/public:"
        ls -la backend/public
    
    # Upload artifact
    - name: Upload deployment artifact
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: |
          backend/dist
          backend/public
          backend/package.json
          backend/package-lock.json
          backend/app.yaml
          backend/.gcloudignore

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download deployment artifact
      uses: actions/download-artifact@v4
      with:
        name: deployment-package
        path: backend-deploy
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Create .gcloudignore
      working-directory: ./backend-deploy
      run: |
        cat > .gcloudignore << 'IGNORE'
        .gcloudignore
        .git
        .gitignore
        node_modules/
        src/
        *.ts
        *.test.js
        coverage/
        .env
        .env.local
        README.md
        *.log
        tests/
        __tests__/
        IGNORE
    
    - name: Deploy to App Engine
      working-directory: ./backend-deploy
      run: |
        # Install only production dependencies
        npm ci --only=production || npm install --only=production
        
        # Deploy
        gcloud app deploy app.yaml \
          --project=${{ env.PROJECT_ID }} \
          --quiet \
          --promote
    
    - name: Verify deployment
      run: |
        echo "🚀 Deployed to: https://${{ env.PROJECT_ID }}.appspot.com"
        sleep 45
        echo "Testing API health..."
        curl -f https://${{ env.PROJECT_ID }}.appspot.com/api/health || echo "Health check still warming up"
        echo "Testing scraper health..."  
        curl -f https://${{ env.PROJECT_ID }}.appspot.com/api/scraper/health || echo "Scraper check still warming up"