name: Test

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Test Backend
      working-directory: ./backend
      run: |
        npm install
        npm run build
        npm test -- --passWithNoTests || true
    
    - name: Test Frontend
      working-directory: ./frontend
      run: |
        npm install
        npm test -- --passWithNoTests --watchAll=false || true