name: Test

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          backend/node_modules
          frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    
    - name: Test Backend
      working-directory: ./backend
      run: |
        npm install
        npm run build
        npm test -- --passWithNoTests
    
    - name: Test Frontend
      working-directory: ./frontend
      run: |
        npm install
        npm test -- --passWithNoTests --watchAll=false
    
    - name: Build check
      run: |
        cd backend && npm run build
        cd ../frontend && npm run build